### ISSUE TITLE
Exporting designs with helix groups to cadnano v2

### ISSUE THREAD

**Issue by tcosmo** [UC-Davis-molecular-computing/scadnano-python-package#132]
Designs with helix groups sharing the same grid should be exportable to cadnano v2.

**Comment by tcosmo** [comment]
@dave-doty : the file "scadnano-python-package/tests_inputs/cadnano_v2_export/test_6_helix_bundle_honeycomb.sc" was explicitely being ignored in .gitignored whereas the unittest TestExportCadnanoV2.test_6_helix_bundle_honeycomb explicitely requires the file. Indeed, the test is lazy and does not code the design in scadnano but directly load the .sc file which is one of the examples featured in scadnano.org. 

Either you are fine with this execption (i.e. it is the only .sc file not ignored in scadnano-python-package/tests_inputs/cadnano_v2_export/) either I can copy paster the design generation from the corresponding examply py file.

**Comment by tcosmo** [comment]
This issue is fixed by the pull request https://github.com/UC-Davis-molecular-computing/scadnano-python-package/pull/133

**Comment by dave-doty** [comment]
I'm not sure exactly how this file was being used.

Mostly I just don't want files in the repo to change just because we run the unit tests. I don't care which files we ignore and which we track, but I prefer if anything we track doesn't change just as a result of running unit tests. (So we can stop ignoring this one if that's the case here.)

**Comment by tcosmo** [comment]
Yeah this file is only being read by the test but not changed by the run.

**Comment by tcosmo** [comment]
@dave-doty oligo names are not stored under cadnano v2 file format, only comes with cadnano v2.5
